// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

package javafxbrowser.rpc;

public interface ByteArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcurlconn.ByteArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 conId = 1;</code>
   */
  long getConId();

  /**
   * <code>optional bytes array = 2;</code>
   */
  com.google.protobuf.ByteString getArray();
}
