// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

package javafxbrowser.rpc;

/**
 * Protobuf type {@code rpcurlconn.ByteArray}
 */
public  final class ByteArray extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rpcurlconn.ByteArray)
    ByteArrayOrBuilder {
  // Use ByteArray.newBuilder() to construct.
  private ByteArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ByteArray() {
    conId_ = 0L;
    array_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ByteArray(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            conId_ = input.readInt64();
            break;
          }
          case 18: {

            array_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return javafxbrowser.rpc.RPCURLConnection.internal_static_rpcurlconn_ByteArray_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return javafxbrowser.rpc.RPCURLConnection.internal_static_rpcurlconn_ByteArray_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            javafxbrowser.rpc.ByteArray.class, javafxbrowser.rpc.ByteArray.Builder.class);
  }

  public static final int CONID_FIELD_NUMBER = 1;
  private long conId_;
  /**
   * <code>optional int64 conId = 1;</code>
   */
  public long getConId() {
    return conId_;
  }

  public static final int ARRAY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString array_;
  /**
   * <code>optional bytes array = 2;</code>
   */
  public com.google.protobuf.ByteString getArray() {
    return array_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (conId_ != 0L) {
      output.writeInt64(1, conId_);
    }
    if (!array_.isEmpty()) {
      output.writeBytes(2, array_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (conId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, conId_);
    }
    if (!array_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, array_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof javafxbrowser.rpc.ByteArray)) {
      return super.equals(obj);
    }
    javafxbrowser.rpc.ByteArray other = (javafxbrowser.rpc.ByteArray) obj;

    boolean result = true;
    result = result && (getConId()
        == other.getConId());
    result = result && getArray()
        .equals(other.getArray());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + CONID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getConId());
    hash = (37 * hash) + ARRAY_FIELD_NUMBER;
    hash = (53 * hash) + getArray().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static javafxbrowser.rpc.ByteArray parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafxbrowser.rpc.ByteArray parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafxbrowser.rpc.ByteArray parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafxbrowser.rpc.ByteArray parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafxbrowser.rpc.ByteArray parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafxbrowser.rpc.ByteArray parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static javafxbrowser.rpc.ByteArray parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static javafxbrowser.rpc.ByteArray parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static javafxbrowser.rpc.ByteArray parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafxbrowser.rpc.ByteArray parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(javafxbrowser.rpc.ByteArray prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code rpcurlconn.ByteArray}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rpcurlconn.ByteArray)
      javafxbrowser.rpc.ByteArrayOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return javafxbrowser.rpc.RPCURLConnection.internal_static_rpcurlconn_ByteArray_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return javafxbrowser.rpc.RPCURLConnection.internal_static_rpcurlconn_ByteArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              javafxbrowser.rpc.ByteArray.class, javafxbrowser.rpc.ByteArray.Builder.class);
    }

    // Construct using javafxbrowser.rpc.ByteArray.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      conId_ = 0L;

      array_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return javafxbrowser.rpc.RPCURLConnection.internal_static_rpcurlconn_ByteArray_descriptor;
    }

    public javafxbrowser.rpc.ByteArray getDefaultInstanceForType() {
      return javafxbrowser.rpc.ByteArray.getDefaultInstance();
    }

    public javafxbrowser.rpc.ByteArray build() {
      javafxbrowser.rpc.ByteArray result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public javafxbrowser.rpc.ByteArray buildPartial() {
      javafxbrowser.rpc.ByteArray result = new javafxbrowser.rpc.ByteArray(this);
      result.conId_ = conId_;
      result.array_ = array_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof javafxbrowser.rpc.ByteArray) {
        return mergeFrom((javafxbrowser.rpc.ByteArray)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(javafxbrowser.rpc.ByteArray other) {
      if (other == javafxbrowser.rpc.ByteArray.getDefaultInstance()) return this;
      if (other.getConId() != 0L) {
        setConId(other.getConId());
      }
      if (other.getArray() != com.google.protobuf.ByteString.EMPTY) {
        setArray(other.getArray());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      javafxbrowser.rpc.ByteArray parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (javafxbrowser.rpc.ByteArray) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long conId_ ;
    /**
     * <code>optional int64 conId = 1;</code>
     */
    public long getConId() {
      return conId_;
    }
    /**
     * <code>optional int64 conId = 1;</code>
     */
    public Builder setConId(long value) {
      
      conId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 conId = 1;</code>
     */
    public Builder clearConId() {
      
      conId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString array_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes array = 2;</code>
     */
    public com.google.protobuf.ByteString getArray() {
      return array_;
    }
    /**
     * <code>optional bytes array = 2;</code>
     */
    public Builder setArray(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      array_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes array = 2;</code>
     */
    public Builder clearArray() {
      
      array_ = getDefaultInstance().getArray();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:rpcurlconn.ByteArray)
  }

  // @@protoc_insertion_point(class_scope:rpcurlconn.ByteArray)
  private static final javafxbrowser.rpc.ByteArray DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new javafxbrowser.rpc.ByteArray();
  }

  public static javafxbrowser.rpc.ByteArray getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ByteArray>
      PARSER = new com.google.protobuf.AbstractParser<ByteArray>() {
    public ByteArray parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ByteArray(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ByteArray> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ByteArray> getParserForType() {
    return PARSER;
  }

  public javafxbrowser.rpc.ByteArray getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

