// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `rpc.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package javafxbrowser.rpc;

public interface ClientWPPrx extends Ice.ObjectPrx
{
    public void updateConfig(javafxbrowser.cfg.BrowserConfigurator conf);

    public void updateConfig(javafxbrowser.cfg.BrowserConfigurator conf, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateConfig(javafxbrowser.cfg.BrowserConfigurator conf);

    public Ice.AsyncResult begin_updateConfig(javafxbrowser.cfg.BrowserConfigurator conf, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateConfig(javafxbrowser.cfg.BrowserConfigurator conf, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateConfig(javafxbrowser.cfg.BrowserConfigurator conf, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateConfig(javafxbrowser.cfg.BrowserConfigurator conf, Callback_ClientWP_updateConfig __cb);

    public Ice.AsyncResult begin_updateConfig(javafxbrowser.cfg.BrowserConfigurator conf, java.util.Map<String, String> __ctx, Callback_ClientWP_updateConfig __cb);

    public Ice.AsyncResult begin_updateConfig(javafxbrowser.cfg.BrowserConfigurator conf, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_updateConfig(javafxbrowser.cfg.BrowserConfigurator conf, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_updateConfig(javafxbrowser.cfg.BrowserConfigurator conf, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_updateConfig(javafxbrowser.cfg.BrowserConfigurator conf, 
                                              java.util.Map<String, String> __ctx, 
                                              IceInternal.Functional_VoidCallback __responseCb, 
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                              IceInternal.Functional_BoolCallback __sentCb);

    public void end_updateConfig(Ice.AsyncResult __result);
}
