// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package javafxbrowser.rpc;

public interface ConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:internalrpc.Config)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string homepage = 1;</code>
   */
  java.lang.String getHomepage();
  /**
   * <code>optional string homepage = 1;</code>
   */
  com.google.protobuf.ByteString
      getHomepageBytes();

  /**
   * <code>optional string defaultDownloadDirectory = 2;</code>
   */
  java.lang.String getDefaultDownloadDirectory();
  /**
   * <code>optional string defaultDownloadDirectory = 2;</code>
   */
  com.google.protobuf.ByteString
      getDefaultDownloadDirectoryBytes();

  /**
   * <code>optional int32 idDefaultSearchEngine = 3;</code>
   */
  int getIdDefaultSearchEngine();

  /**
   * <code>optional bool openNewTabEmpty = 4;</code>
   */
  boolean getOpenNewTabEmpty();

  /**
   * <code>optional bool showMenuBar = 5;</code>
   */
  boolean getShowMenuBar();

  /**
   * <code>optional bool showNavigationBar = 6;</code>
   */
  boolean getShowNavigationBar();

  /**
   * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
   */
  java.util.List<javafxbrowser.rpc.SearchEngine> 
      getSearchEnginesList();
  /**
   * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
   */
  javafxbrowser.rpc.SearchEngine getSearchEngines(int index);
  /**
   * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
   */
  int getSearchEnginesCount();
  /**
   * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
   */
  java.util.List<? extends javafxbrowser.rpc.SearchEngineOrBuilder> 
      getSearchEnginesOrBuilderList();
  /**
   * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
   */
  javafxbrowser.rpc.SearchEngineOrBuilder getSearchEnginesOrBuilder(
      int index);
}
