// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `rpc.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package javafxbrowser.rpc;

public final class ConfigObjHelper
{
    public static void
    write(IceInternal.BasicStream __os, javafxbrowser.cfg.BrowserConfigurator __v)
    {
        __os.writeSerializable(__v);
    }

    public static javafxbrowser.cfg.BrowserConfigurator
    read(IceInternal.BasicStream __is)
    {
        javafxbrowser.cfg.BrowserConfigurator __v;
        __v = (javafxbrowser.cfg.BrowserConfigurator)__is.readSerializable();
        return __v;
    }
}
