// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package javafxbrowser.rpc;

/**
 * Protobuf type {@code internalrpc.Config}
 */
public  final class Config extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:internalrpc.Config)
    ConfigOrBuilder {
  // Use Config.newBuilder() to construct.
  private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Config() {
    homepage_ = "";
    defaultDownloadDirectory_ = "";
    idDefaultSearchEngine_ = 0;
    openNewTabEmpty_ = false;
    showMenuBar_ = false;
    showNavigationBar_ = false;
    searchEngines_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Config(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            homepage_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            defaultDownloadDirectory_ = s;
            break;
          }
          case 24: {

            idDefaultSearchEngine_ = input.readInt32();
            break;
          }
          case 32: {

            openNewTabEmpty_ = input.readBool();
            break;
          }
          case 40: {

            showMenuBar_ = input.readBool();
            break;
          }
          case 48: {

            showNavigationBar_ = input.readBool();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              searchEngines_ = new java.util.ArrayList<javafxbrowser.rpc.SearchEngine>();
              mutable_bitField0_ |= 0x00000040;
            }
            searchEngines_.add(
                input.readMessage(javafxbrowser.rpc.SearchEngine.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        searchEngines_ = java.util.Collections.unmodifiableList(searchEngines_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return javafxbrowser.rpc.InternalRPCProto.internal_static_internalrpc_Config_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return javafxbrowser.rpc.InternalRPCProto.internal_static_internalrpc_Config_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            javafxbrowser.rpc.Config.class, javafxbrowser.rpc.Config.Builder.class);
  }

  private int bitField0_;
  public static final int HOMEPAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object homepage_;
  /**
   * <code>optional string homepage = 1;</code>
   */
  public java.lang.String getHomepage() {
    java.lang.Object ref = homepage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      homepage_ = s;
      return s;
    }
  }
  /**
   * <code>optional string homepage = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHomepageBytes() {
    java.lang.Object ref = homepage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      homepage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFAULTDOWNLOADDIRECTORY_FIELD_NUMBER = 2;
  private volatile java.lang.Object defaultDownloadDirectory_;
  /**
   * <code>optional string defaultDownloadDirectory = 2;</code>
   */
  public java.lang.String getDefaultDownloadDirectory() {
    java.lang.Object ref = defaultDownloadDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      defaultDownloadDirectory_ = s;
      return s;
    }
  }
  /**
   * <code>optional string defaultDownloadDirectory = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDefaultDownloadDirectoryBytes() {
    java.lang.Object ref = defaultDownloadDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      defaultDownloadDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDDEFAULTSEARCHENGINE_FIELD_NUMBER = 3;
  private int idDefaultSearchEngine_;
  /**
   * <code>optional int32 idDefaultSearchEngine = 3;</code>
   */
  public int getIdDefaultSearchEngine() {
    return idDefaultSearchEngine_;
  }

  public static final int OPENNEWTABEMPTY_FIELD_NUMBER = 4;
  private boolean openNewTabEmpty_;
  /**
   * <code>optional bool openNewTabEmpty = 4;</code>
   */
  public boolean getOpenNewTabEmpty() {
    return openNewTabEmpty_;
  }

  public static final int SHOWMENUBAR_FIELD_NUMBER = 5;
  private boolean showMenuBar_;
  /**
   * <code>optional bool showMenuBar = 5;</code>
   */
  public boolean getShowMenuBar() {
    return showMenuBar_;
  }

  public static final int SHOWNAVIGATIONBAR_FIELD_NUMBER = 6;
  private boolean showNavigationBar_;
  /**
   * <code>optional bool showNavigationBar = 6;</code>
   */
  public boolean getShowNavigationBar() {
    return showNavigationBar_;
  }

  public static final int SEARCHENGINES_FIELD_NUMBER = 7;
  private java.util.List<javafxbrowser.rpc.SearchEngine> searchEngines_;
  /**
   * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
   */
  public java.util.List<javafxbrowser.rpc.SearchEngine> getSearchEnginesList() {
    return searchEngines_;
  }
  /**
   * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
   */
  public java.util.List<? extends javafxbrowser.rpc.SearchEngineOrBuilder> 
      getSearchEnginesOrBuilderList() {
    return searchEngines_;
  }
  /**
   * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
   */
  public int getSearchEnginesCount() {
    return searchEngines_.size();
  }
  /**
   * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
   */
  public javafxbrowser.rpc.SearchEngine getSearchEngines(int index) {
    return searchEngines_.get(index);
  }
  /**
   * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
   */
  public javafxbrowser.rpc.SearchEngineOrBuilder getSearchEnginesOrBuilder(
      int index) {
    return searchEngines_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHomepageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, homepage_);
    }
    if (!getDefaultDownloadDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, defaultDownloadDirectory_);
    }
    if (idDefaultSearchEngine_ != 0) {
      output.writeInt32(3, idDefaultSearchEngine_);
    }
    if (openNewTabEmpty_ != false) {
      output.writeBool(4, openNewTabEmpty_);
    }
    if (showMenuBar_ != false) {
      output.writeBool(5, showMenuBar_);
    }
    if (showNavigationBar_ != false) {
      output.writeBool(6, showNavigationBar_);
    }
    for (int i = 0; i < searchEngines_.size(); i++) {
      output.writeMessage(7, searchEngines_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHomepageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, homepage_);
    }
    if (!getDefaultDownloadDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, defaultDownloadDirectory_);
    }
    if (idDefaultSearchEngine_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, idDefaultSearchEngine_);
    }
    if (openNewTabEmpty_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, openNewTabEmpty_);
    }
    if (showMenuBar_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, showMenuBar_);
    }
    if (showNavigationBar_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, showNavigationBar_);
    }
    for (int i = 0; i < searchEngines_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, searchEngines_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof javafxbrowser.rpc.Config)) {
      return super.equals(obj);
    }
    javafxbrowser.rpc.Config other = (javafxbrowser.rpc.Config) obj;

    boolean result = true;
    result = result && getHomepage()
        .equals(other.getHomepage());
    result = result && getDefaultDownloadDirectory()
        .equals(other.getDefaultDownloadDirectory());
    result = result && (getIdDefaultSearchEngine()
        == other.getIdDefaultSearchEngine());
    result = result && (getOpenNewTabEmpty()
        == other.getOpenNewTabEmpty());
    result = result && (getShowMenuBar()
        == other.getShowMenuBar());
    result = result && (getShowNavigationBar()
        == other.getShowNavigationBar());
    result = result && getSearchEnginesList()
        .equals(other.getSearchEnginesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + HOMEPAGE_FIELD_NUMBER;
    hash = (53 * hash) + getHomepage().hashCode();
    hash = (37 * hash) + DEFAULTDOWNLOADDIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getDefaultDownloadDirectory().hashCode();
    hash = (37 * hash) + IDDEFAULTSEARCHENGINE_FIELD_NUMBER;
    hash = (53 * hash) + getIdDefaultSearchEngine();
    hash = (37 * hash) + OPENNEWTABEMPTY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOpenNewTabEmpty());
    hash = (37 * hash) + SHOWMENUBAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getShowMenuBar());
    hash = (37 * hash) + SHOWNAVIGATIONBAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getShowNavigationBar());
    if (getSearchEnginesCount() > 0) {
      hash = (37 * hash) + SEARCHENGINES_FIELD_NUMBER;
      hash = (53 * hash) + getSearchEnginesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static javafxbrowser.rpc.Config parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafxbrowser.rpc.Config parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafxbrowser.rpc.Config parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static javafxbrowser.rpc.Config parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static javafxbrowser.rpc.Config parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafxbrowser.rpc.Config parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static javafxbrowser.rpc.Config parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static javafxbrowser.rpc.Config parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static javafxbrowser.rpc.Config parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static javafxbrowser.rpc.Config parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(javafxbrowser.rpc.Config prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code internalrpc.Config}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:internalrpc.Config)
      javafxbrowser.rpc.ConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return javafxbrowser.rpc.InternalRPCProto.internal_static_internalrpc_Config_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return javafxbrowser.rpc.InternalRPCProto.internal_static_internalrpc_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              javafxbrowser.rpc.Config.class, javafxbrowser.rpc.Config.Builder.class);
    }

    // Construct using javafxbrowser.rpc.Config.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSearchEnginesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      homepage_ = "";

      defaultDownloadDirectory_ = "";

      idDefaultSearchEngine_ = 0;

      openNewTabEmpty_ = false;

      showMenuBar_ = false;

      showNavigationBar_ = false;

      if (searchEnginesBuilder_ == null) {
        searchEngines_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        searchEnginesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return javafxbrowser.rpc.InternalRPCProto.internal_static_internalrpc_Config_descriptor;
    }

    public javafxbrowser.rpc.Config getDefaultInstanceForType() {
      return javafxbrowser.rpc.Config.getDefaultInstance();
    }

    public javafxbrowser.rpc.Config build() {
      javafxbrowser.rpc.Config result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public javafxbrowser.rpc.Config buildPartial() {
      javafxbrowser.rpc.Config result = new javafxbrowser.rpc.Config(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.homepage_ = homepage_;
      result.defaultDownloadDirectory_ = defaultDownloadDirectory_;
      result.idDefaultSearchEngine_ = idDefaultSearchEngine_;
      result.openNewTabEmpty_ = openNewTabEmpty_;
      result.showMenuBar_ = showMenuBar_;
      result.showNavigationBar_ = showNavigationBar_;
      if (searchEnginesBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          searchEngines_ = java.util.Collections.unmodifiableList(searchEngines_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.searchEngines_ = searchEngines_;
      } else {
        result.searchEngines_ = searchEnginesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof javafxbrowser.rpc.Config) {
        return mergeFrom((javafxbrowser.rpc.Config)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(javafxbrowser.rpc.Config other) {
      if (other == javafxbrowser.rpc.Config.getDefaultInstance()) return this;
      if (!other.getHomepage().isEmpty()) {
        homepage_ = other.homepage_;
        onChanged();
      }
      if (!other.getDefaultDownloadDirectory().isEmpty()) {
        defaultDownloadDirectory_ = other.defaultDownloadDirectory_;
        onChanged();
      }
      if (other.getIdDefaultSearchEngine() != 0) {
        setIdDefaultSearchEngine(other.getIdDefaultSearchEngine());
      }
      if (other.getOpenNewTabEmpty() != false) {
        setOpenNewTabEmpty(other.getOpenNewTabEmpty());
      }
      if (other.getShowMenuBar() != false) {
        setShowMenuBar(other.getShowMenuBar());
      }
      if (other.getShowNavigationBar() != false) {
        setShowNavigationBar(other.getShowNavigationBar());
      }
      if (searchEnginesBuilder_ == null) {
        if (!other.searchEngines_.isEmpty()) {
          if (searchEngines_.isEmpty()) {
            searchEngines_ = other.searchEngines_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureSearchEnginesIsMutable();
            searchEngines_.addAll(other.searchEngines_);
          }
          onChanged();
        }
      } else {
        if (!other.searchEngines_.isEmpty()) {
          if (searchEnginesBuilder_.isEmpty()) {
            searchEnginesBuilder_.dispose();
            searchEnginesBuilder_ = null;
            searchEngines_ = other.searchEngines_;
            bitField0_ = (bitField0_ & ~0x00000040);
            searchEnginesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSearchEnginesFieldBuilder() : null;
          } else {
            searchEnginesBuilder_.addAllMessages(other.searchEngines_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      javafxbrowser.rpc.Config parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (javafxbrowser.rpc.Config) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object homepage_ = "";
    /**
     * <code>optional string homepage = 1;</code>
     */
    public java.lang.String getHomepage() {
      java.lang.Object ref = homepage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        homepage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string homepage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHomepageBytes() {
      java.lang.Object ref = homepage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        homepage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string homepage = 1;</code>
     */
    public Builder setHomepage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      homepage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string homepage = 1;</code>
     */
    public Builder clearHomepage() {
      
      homepage_ = getDefaultInstance().getHomepage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string homepage = 1;</code>
     */
    public Builder setHomepageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      homepage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object defaultDownloadDirectory_ = "";
    /**
     * <code>optional string defaultDownloadDirectory = 2;</code>
     */
    public java.lang.String getDefaultDownloadDirectory() {
      java.lang.Object ref = defaultDownloadDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultDownloadDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string defaultDownloadDirectory = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDefaultDownloadDirectoryBytes() {
      java.lang.Object ref = defaultDownloadDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultDownloadDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string defaultDownloadDirectory = 2;</code>
     */
    public Builder setDefaultDownloadDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      defaultDownloadDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string defaultDownloadDirectory = 2;</code>
     */
    public Builder clearDefaultDownloadDirectory() {
      
      defaultDownloadDirectory_ = getDefaultInstance().getDefaultDownloadDirectory();
      onChanged();
      return this;
    }
    /**
     * <code>optional string defaultDownloadDirectory = 2;</code>
     */
    public Builder setDefaultDownloadDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      defaultDownloadDirectory_ = value;
      onChanged();
      return this;
    }

    private int idDefaultSearchEngine_ ;
    /**
     * <code>optional int32 idDefaultSearchEngine = 3;</code>
     */
    public int getIdDefaultSearchEngine() {
      return idDefaultSearchEngine_;
    }
    /**
     * <code>optional int32 idDefaultSearchEngine = 3;</code>
     */
    public Builder setIdDefaultSearchEngine(int value) {
      
      idDefaultSearchEngine_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 idDefaultSearchEngine = 3;</code>
     */
    public Builder clearIdDefaultSearchEngine() {
      
      idDefaultSearchEngine_ = 0;
      onChanged();
      return this;
    }

    private boolean openNewTabEmpty_ ;
    /**
     * <code>optional bool openNewTabEmpty = 4;</code>
     */
    public boolean getOpenNewTabEmpty() {
      return openNewTabEmpty_;
    }
    /**
     * <code>optional bool openNewTabEmpty = 4;</code>
     */
    public Builder setOpenNewTabEmpty(boolean value) {
      
      openNewTabEmpty_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool openNewTabEmpty = 4;</code>
     */
    public Builder clearOpenNewTabEmpty() {
      
      openNewTabEmpty_ = false;
      onChanged();
      return this;
    }

    private boolean showMenuBar_ ;
    /**
     * <code>optional bool showMenuBar = 5;</code>
     */
    public boolean getShowMenuBar() {
      return showMenuBar_;
    }
    /**
     * <code>optional bool showMenuBar = 5;</code>
     */
    public Builder setShowMenuBar(boolean value) {
      
      showMenuBar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool showMenuBar = 5;</code>
     */
    public Builder clearShowMenuBar() {
      
      showMenuBar_ = false;
      onChanged();
      return this;
    }

    private boolean showNavigationBar_ ;
    /**
     * <code>optional bool showNavigationBar = 6;</code>
     */
    public boolean getShowNavigationBar() {
      return showNavigationBar_;
    }
    /**
     * <code>optional bool showNavigationBar = 6;</code>
     */
    public Builder setShowNavigationBar(boolean value) {
      
      showNavigationBar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool showNavigationBar = 6;</code>
     */
    public Builder clearShowNavigationBar() {
      
      showNavigationBar_ = false;
      onChanged();
      return this;
    }

    private java.util.List<javafxbrowser.rpc.SearchEngine> searchEngines_ =
      java.util.Collections.emptyList();
    private void ensureSearchEnginesIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        searchEngines_ = new java.util.ArrayList<javafxbrowser.rpc.SearchEngine>(searchEngines_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        javafxbrowser.rpc.SearchEngine, javafxbrowser.rpc.SearchEngine.Builder, javafxbrowser.rpc.SearchEngineOrBuilder> searchEnginesBuilder_;

    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public java.util.List<javafxbrowser.rpc.SearchEngine> getSearchEnginesList() {
      if (searchEnginesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(searchEngines_);
      } else {
        return searchEnginesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public int getSearchEnginesCount() {
      if (searchEnginesBuilder_ == null) {
        return searchEngines_.size();
      } else {
        return searchEnginesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public javafxbrowser.rpc.SearchEngine getSearchEngines(int index) {
      if (searchEnginesBuilder_ == null) {
        return searchEngines_.get(index);
      } else {
        return searchEnginesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public Builder setSearchEngines(
        int index, javafxbrowser.rpc.SearchEngine value) {
      if (searchEnginesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSearchEnginesIsMutable();
        searchEngines_.set(index, value);
        onChanged();
      } else {
        searchEnginesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public Builder setSearchEngines(
        int index, javafxbrowser.rpc.SearchEngine.Builder builderForValue) {
      if (searchEnginesBuilder_ == null) {
        ensureSearchEnginesIsMutable();
        searchEngines_.set(index, builderForValue.build());
        onChanged();
      } else {
        searchEnginesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public Builder addSearchEngines(javafxbrowser.rpc.SearchEngine value) {
      if (searchEnginesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSearchEnginesIsMutable();
        searchEngines_.add(value);
        onChanged();
      } else {
        searchEnginesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public Builder addSearchEngines(
        int index, javafxbrowser.rpc.SearchEngine value) {
      if (searchEnginesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSearchEnginesIsMutable();
        searchEngines_.add(index, value);
        onChanged();
      } else {
        searchEnginesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public Builder addSearchEngines(
        javafxbrowser.rpc.SearchEngine.Builder builderForValue) {
      if (searchEnginesBuilder_ == null) {
        ensureSearchEnginesIsMutable();
        searchEngines_.add(builderForValue.build());
        onChanged();
      } else {
        searchEnginesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public Builder addSearchEngines(
        int index, javafxbrowser.rpc.SearchEngine.Builder builderForValue) {
      if (searchEnginesBuilder_ == null) {
        ensureSearchEnginesIsMutable();
        searchEngines_.add(index, builderForValue.build());
        onChanged();
      } else {
        searchEnginesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public Builder addAllSearchEngines(
        java.lang.Iterable<? extends javafxbrowser.rpc.SearchEngine> values) {
      if (searchEnginesBuilder_ == null) {
        ensureSearchEnginesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, searchEngines_);
        onChanged();
      } else {
        searchEnginesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public Builder clearSearchEngines() {
      if (searchEnginesBuilder_ == null) {
        searchEngines_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        searchEnginesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public Builder removeSearchEngines(int index) {
      if (searchEnginesBuilder_ == null) {
        ensureSearchEnginesIsMutable();
        searchEngines_.remove(index);
        onChanged();
      } else {
        searchEnginesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public javafxbrowser.rpc.SearchEngine.Builder getSearchEnginesBuilder(
        int index) {
      return getSearchEnginesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public javafxbrowser.rpc.SearchEngineOrBuilder getSearchEnginesOrBuilder(
        int index) {
      if (searchEnginesBuilder_ == null) {
        return searchEngines_.get(index);  } else {
        return searchEnginesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public java.util.List<? extends javafxbrowser.rpc.SearchEngineOrBuilder> 
         getSearchEnginesOrBuilderList() {
      if (searchEnginesBuilder_ != null) {
        return searchEnginesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(searchEngines_);
      }
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public javafxbrowser.rpc.SearchEngine.Builder addSearchEnginesBuilder() {
      return getSearchEnginesFieldBuilder().addBuilder(
          javafxbrowser.rpc.SearchEngine.getDefaultInstance());
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public javafxbrowser.rpc.SearchEngine.Builder addSearchEnginesBuilder(
        int index) {
      return getSearchEnginesFieldBuilder().addBuilder(
          index, javafxbrowser.rpc.SearchEngine.getDefaultInstance());
    }
    /**
     * <code>repeated .internalrpc.SearchEngine searchEngines = 7;</code>
     */
    public java.util.List<javafxbrowser.rpc.SearchEngine.Builder> 
         getSearchEnginesBuilderList() {
      return getSearchEnginesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        javafxbrowser.rpc.SearchEngine, javafxbrowser.rpc.SearchEngine.Builder, javafxbrowser.rpc.SearchEngineOrBuilder> 
        getSearchEnginesFieldBuilder() {
      if (searchEnginesBuilder_ == null) {
        searchEnginesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            javafxbrowser.rpc.SearchEngine, javafxbrowser.rpc.SearchEngine.Builder, javafxbrowser.rpc.SearchEngineOrBuilder>(
                searchEngines_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        searchEngines_ = null;
      }
      return searchEnginesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:internalrpc.Config)
  }

  // @@protoc_insertion_point(class_scope:internalrpc.Config)
  private static final javafxbrowser.rpc.Config DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new javafxbrowser.rpc.Config();
  }

  public static javafxbrowser.rpc.Config getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Config>
      PARSER = new com.google.protobuf.AbstractParser<Config>() {
    public Config parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Config(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Config> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Config> getParserForType() {
    return PARSER;
  }

  public javafxbrowser.rpc.Config getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

