// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

package javafxbrowser.rpc;

public interface FieldIntOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcurlconn.FieldInt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 conId = 1;</code>
   */
  long getConId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 default = 3;</code>
   */
  int getDefault();
}
