// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

package javafxbrowser.rpc;

public interface IntOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcurlconn.Int)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 conId = 1;</code>
   */
  long getConId();

  /**
   * <code>optional int32 value = 2;</code>
   */
  int getValue();
}
