// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

package javafxbrowser.rpc;

public interface KeyValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcurlconn.KeyValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 conId = 1;</code>
   */
  long getConId();

  /**
   * <code>optional string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>optional string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>optional string value = 3;</code>
   */
  java.lang.String getValue();
  /**
   * <code>optional string value = 3;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
