// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

package javafxbrowser.rpc;

public final class RPCURLConnection {
  private RPCURLConnection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_ID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_ID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_Int_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_Int_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_Long_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_Long_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_StringObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_StringObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_Boolean_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_Boolean_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_Void_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_Void_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_ByteArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_ByteArray_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_ByteArrayOffset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_ByteArrayOffset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_FieldInt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_FieldInt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_FieldLong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_FieldLong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpcurlconn_KeyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpcurlconn_KeyValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tnet.proto\022\nrpcurlconn\"\023\n\002ID\022\r\n\005conId\030\001" +
      " \001(\003\"#\n\003Int\022\r\n\005conId\030\001 \001(\003\022\r\n\005value\030\002 \001(" +
      "\005\"$\n\004Long\022\r\n\005conId\030\001 \001(\003\022\r\n\005value\030\002 \001(\003\"" +
      ",\n\014StringObject\022\r\n\005conId\030\001 \001(\003\022\r\n\005value\030" +
      "\002 \001(\t\"\'\n\007Boolean\022\r\n\005conId\030\001 \001(\003\022\r\n\005value" +
      "\030\002 \001(\010\"\025\n\004Void\022\r\n\005conId\030\001 \001(\003\")\n\tByteArr" +
      "ay\022\r\n\005conId\030\001 \001(\003\022\r\n\005array\030\002 \001(\014\"L\n\017Byte" +
      "ArrayOffset\022\r\n\005conId\030\001 \001(\003\022\r\n\005array\030\002 \001(" +
      "\014\022\016\n\006offset\030\003 \001(\005\022\013\n\003len\030\004 \001(\005\"8\n\010FieldI" +
      "nt\022\r\n\005conId\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\017\n\007defau",
      "lt\030\003 \001(\005\"9\n\tFieldLong\022\r\n\005conId\030\001 \001(\003\022\014\n\004" +
      "name\030\002 \001(\t\022\017\n\007default\030\003 \001(\003\"5\n\010KeyValue\022" +
      "\r\n\005conId\030\001 \001(\003\022\013\n\003key\030\002 \001(\t\022\r\n\005value\030\003 \001" +
      "(\t2\203\030\n\013URLPetition\0229\n\013constructor\022\030.rpcu" +
      "rlconn.StringObject\032\016.rpcurlconn.ID\"\000\022/\n" +
      "\007connect\022\020.rpcurlconn.Void\032\020.rpcurlconn." +
      "Void\"\000\0228\n\021setConnectTimeout\022\017.rpcurlconn" +
      ".Int\032\020.rpcurlconn.Void\"\000\0228\n\021getConnectTi" +
      "meout\022\020.rpcurlconn.Void\032\017.rpcurlconn.Int" +
      "\"\000\0225\n\016setReadTimeout\022\017.rpcurlconn.Int\032\020.",
      "rpcurlconn.Void\"\000\0225\n\016getReadTimeout\022\020.rp" +
      "curlconn.Void\032\017.rpcurlconn.Int\"\000\0227\n\020getC" +
      "ontentLength\022\020.rpcurlconn.Void\032\017.rpcurlc" +
      "onn.Int\"\000\022<\n\024getContentLengthLong\022\020.rpcu" +
      "rlconn.Void\032\020.rpcurlconn.Long\"\000\022>\n\016getCo" +
      "ntentType\022\020.rpcurlconn.Void\032\030.rpcurlconn" +
      ".StringObject\"\000\022B\n\022getContentEncoding\022\020." +
      "rpcurlconn.Void\032\030.rpcurlconn.StringObjec" +
      "t\"\000\0225\n\rgetExpiration\022\020.rpcurlconn.Void\032\020" +
      ".rpcurlconn.Long\"\000\022/\n\007getDate\022\020.rpcurlco",
      "nn.Void\032\020.rpcurlconn.Long\"\000\0227\n\017getLastMo" +
      "dified\022\020.rpcurlconn.Void\032\020.rpcurlconn.Lo" +
      "ng\"\000\022F\n\016getHeaderField\022\030.rpcurlconn.Stri" +
      "ngObject\032\030.rpcurlconn.StringObject\"\000\022<\n\021" +
      "getHeaderFieldInt\022\024.rpcurlconn.FieldInt\032" +
      "\017.rpcurlconn.Int\"\000\022?\n\022getHeaderFieldLong" +
      "\022\025.rpcurlconn.FieldLong\032\020.rpcurlconn.Lon" +
      "g\"\000\022?\n\022getHeaderFieldDate\022\025.rpcurlconn.F" +
      "ieldLong\032\020.rpcurlconn.Long\"\000\022@\n\021getHeade" +
      "rFieldKey\022\017.rpcurlconn.Int\032\030.rpcurlconn.",
      "StringObject\"\000\022>\n\016toStringObject\022\020.rpcur" +
      "lconn.Void\032\030.rpcurlconn.StringObject\"\000\0225" +
      "\n\nsetDoInput\022\023.rpcurlconn.Boolean\032\020.rpcu" +
      "rlconn.Void\"\000\0225\n\ngetDoInput\022\020.rpcurlconn" +
      ".Void\032\023.rpcurlconn.Boolean\"\000\0226\n\013setDoOut" +
      "put\022\023.rpcurlconn.Boolean\032\020.rpcurlconn.Vo" +
      "id\"\000\0226\n\013getDoOutput\022\020.rpcurlconn.Void\032\023." +
      "rpcurlconn.Boolean\"\000\022B\n\027setAllowUserInte" +
      "raction\022\023.rpcurlconn.Boolean\032\020.rpcurlcon" +
      "n.Void\"\000\022B\n\027getAllowUserInteraction\022\020.rp",
      "curlconn.Void\032\023.rpcurlconn.Boolean\"\000\022I\n\036" +
      "setDefaultAllowUserInteraction\022\023.rpcurlc" +
      "onn.Boolean\032\020.rpcurlconn.Void\"\000\022I\n\036getDe" +
      "faultAllowUserInteraction\022\020.rpcurlconn.V" +
      "oid\032\023.rpcurlconn.Boolean\"\000\0227\n\014setUseCach" +
      "es\022\023.rpcurlconn.Boolean\032\020.rpcurlconn.Voi" +
      "d\"\000\0227\n\014getUseCaches\022\020.rpcurlconn.Void\032\023." +
      "rpcurlconn.Boolean\"\000\022:\n\022setIfModifiedSin" +
      "ce\022\020.rpcurlconn.Long\032\020.rpcurlconn.Void\"\000" +
      "\022:\n\022getIfModifiedSince\022\020.rpcurlconn.Void",
      "\032\020.rpcurlconn.Long\"\000\022>\n\023getDefaultUseCac" +
      "hes\022\020.rpcurlconn.Void\032\023.rpcurlconn.Boole" +
      "an\"\000\022>\n\023setDefaultUseCaches\022\023.rpcurlconn" +
      ".Boolean\032\020.rpcurlconn.Void\"\000\022>\n\022setReque" +
      "stProperty\022\024.rpcurlconn.KeyValue\032\020.rpcur" +
      "lconn.Void\"\000\022>\n\022addRequestProperty\022\024.rpc" +
      "urlconn.KeyValue\032\020.rpcurlconn.Void\"\000\022J\n\022" +
      "getRequestProperty\022\030.rpcurlconn.StringOb" +
      "ject\032\030.rpcurlconn.StringObject\"\000\022E\n\031setD" +
      "efaultRequestProperty\022\024.rpcurlconn.KeyVa",
      "lue\032\020.rpcurlconn.Void\"\000\022Q\n\031getDefaultReq" +
      "uestProperty\022\030.rpcurlconn.StringObject\032\030" +
      ".rpcurlconn.StringObject\"\000\022P\n\030guessConte" +
      "ntTypeFromName\022\030.rpcurlconn.StringObject" +
      "\032\030.rpcurlconn.StringObject\"\000\0226\n\016getInput" +
      "Stream\022\020.rpcurlconn.Void\032\020.rpcurlconn.Lo" +
      "ng\"\000\0228\n\020InputStreamClose\022\020.rpcurlconn.Vo" +
      "id\032\020.rpcurlconn.Void\"\000\0226\n\017InputStreamRea" +
      "d\022\020.rpcurlconn.Void\032\017.rpcurlconn.Int\"\000\022@" +
      "\n\024InputStreamReadArray\022\025.rpcurlconn.Byte",
      "Array\032\017.rpcurlconn.Int\"\000\022I\n\027InputStreamR" +
      "eadArrayOff\022\033.rpcurlconn.ByteArrayOffset" +
      "\032\017.rpcurlconn.Int\"\000\0227\n\017InputStreamSkip\022\020" +
      ".rpcurlconn.Long\032\020.rpcurlconn.Long\"\000\022;\n\024" +
      "InputStreamAvailable\022\020.rpcurlconn.Void\032\017" +
      ".rpcurlconn.Int\"\000\0226\n\017InputStreamMark\022\017.r" +
      "pcurlconn.Int\032\020.rpcurlconn.Void\"\000\0228\n\020Inp" +
      "utStreamReset\022\020.rpcurlconn.Void\032\020.rpcurl" +
      "conn.Void\"\000\022C\n\030InputStreamMarkSupported\022" +
      "\020.rpcurlconn.Void\032\023.rpcurlconn.Boolean\"\000",
      "B-\n\021javafxbrowser.rpcB\020RPCURLConnectionP" +
      "\001\242\002\003RUCb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rpcurlconn_ID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpcurlconn_ID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_ID_descriptor,
        new java.lang.String[] { "ConId", });
    internal_static_rpcurlconn_Int_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpcurlconn_Int_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_Int_descriptor,
        new java.lang.String[] { "ConId", "Value", });
    internal_static_rpcurlconn_Long_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rpcurlconn_Long_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_Long_descriptor,
        new java.lang.String[] { "ConId", "Value", });
    internal_static_rpcurlconn_StringObject_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_rpcurlconn_StringObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_StringObject_descriptor,
        new java.lang.String[] { "ConId", "Value", });
    internal_static_rpcurlconn_Boolean_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_rpcurlconn_Boolean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_Boolean_descriptor,
        new java.lang.String[] { "ConId", "Value", });
    internal_static_rpcurlconn_Void_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_rpcurlconn_Void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_Void_descriptor,
        new java.lang.String[] { "ConId", });
    internal_static_rpcurlconn_ByteArray_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_rpcurlconn_ByteArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_ByteArray_descriptor,
        new java.lang.String[] { "ConId", "Array", });
    internal_static_rpcurlconn_ByteArrayOffset_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_rpcurlconn_ByteArrayOffset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_ByteArrayOffset_descriptor,
        new java.lang.String[] { "ConId", "Array", "Offset", "Len", });
    internal_static_rpcurlconn_FieldInt_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_rpcurlconn_FieldInt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_FieldInt_descriptor,
        new java.lang.String[] { "ConId", "Name", "Default", });
    internal_static_rpcurlconn_FieldLong_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_rpcurlconn_FieldLong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_FieldLong_descriptor,
        new java.lang.String[] { "ConId", "Name", "Default", });
    internal_static_rpcurlconn_KeyValue_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_rpcurlconn_KeyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpcurlconn_KeyValue_descriptor,
        new java.lang.String[] { "ConId", "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
