// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

package javafxbrowser.rpc;

public interface StreamReadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcurlconn.StreamRead)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 amount = 1;</code>
   */
  int getAmount();

  /**
   * <code>optional bytes array = 2;</code>
   */
  com.google.protobuf.ByteString getArray();
}
