// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net.proto

package javafxbrowser.rpc;

public interface VoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpcurlconn.Void)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 conId = 1;</code>
   */
  long getConId();
}
