// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package javafxbrowser.rpc;

public final class InternalRPCProto {
  private InternalRPCProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_internalrpc_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_internalrpc_Config_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_internalrpc_SearchEngine_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_internalrpc_SearchEngine_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngrpc.proto\022\013internalrpc\"\326\001\n\006Config\022\020\n\010" +
      "homepage\030\001 \001(\t\022 \n\030defaultDownloadDirecto" +
      "ry\030\002 \001(\t\022\035\n\025idDefaultSearchEngine\030\003 \001(\005\022" +
      "\027\n\017openNewTabEmpty\030\004 \001(\010\022\023\n\013showMenuBar\030" +
      "\005 \001(\010\022\031\n\021showNavigationBar\030\006 \001(\010\0220\n\rsear" +
      "chEngines\030\007 \003(\0132\031.internalrpc.SearchEngi" +
      "ne\"5\n\014SearchEngine\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002" +
      " \001(\t\022\013\n\003url\030\003 \001(\t2\202\001\n\016ServerPetition\0227\n\t" +
      "GetConfig\022\023.internalrpc.Config\032\023.interna" +
      "lrpc.Config\"\000\0227\n\tSetConfig\022\023.internalrpc",
      ".Config\032\023.internalrpc.Config\"\000B-\n\021javafx" +
      "browser.rpcB\020InternalRPCProtoP\001\242\002\003IRPb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_internalrpc_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_internalrpc_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_internalrpc_Config_descriptor,
        new java.lang.String[] { "Homepage", "DefaultDownloadDirectory", "IdDefaultSearchEngine", "OpenNewTabEmpty", "ShowMenuBar", "ShowNavigationBar", "SearchEngines", });
    internal_static_internalrpc_SearchEngine_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_internalrpc_SearchEngine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_internalrpc_SearchEngine_descriptor,
        new java.lang.String[] { "Id", "Name", "Url", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
