// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package javafxbrowser.rpc;

public interface SearchEngineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:internalrpc.SearchEngine)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string url = 3;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>optional string url = 3;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
